In [1]:
import torch

In [2]:
data = torch.tensor([[1.,2.,3.,4.]])

In [3]:
fired = torch.zeros_like(data)
fired[data > 1.] = 1.

In [4]:
fired

tensor([[0., 1., 1., 1.]])

In [5]:
data[data > 1.] = 0.

In [8]:
fired[:, [0,1]]

tensor([[0., 1.]])

In [26]:
# fired = torch.tensor([[0., 1., 1., 1.],[1., 0., 1., 1.]])
fired = torch.tensor([[0., 1., 0., 0.],[0., 1., 1., 0.]])

In [27]:
torch.max(fired[:, [0, 1]], 0).values

tensor([0., 1.])

In [28]:
torch.max(fired[:, [2, 3]], 0).values

tensor([1., 0.])

In [31]:
torch.cat((torch.max(fired[:, [0, 1]], 0).values -1, torch.max(fired[:, [2, 3]], 0).values))**2

tensor([1., 0., 1., 0.])

In [33]:
torch.mean(torch.cat((torch.max(fired[:, [0, 1]], 0).values -1, torch.max(fired[:, [2, 3]], 0).values))**2)

tensor(0.5000)

In [38]:
fired[:, torch.arange(torch.arange(10))]

TypeError: arange(): argument 'end' (position 1) must be Number, not Tensor

In [47]:
torch.cat([torch.arange(i+1).unsqueeze(0) for i in range(fired.shape[0])], 0)

RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1 (The offending index is 1)